name: "Go API-RESTAURANT"
description: "Get started with Go Container actions"
author: "Evry Nazyli"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
