name: Integration Test
on: 
  push:
    branches:    
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: nazyli/api-restaurant@master

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello world"
